<?php
namespace app\promotion\controller;
/**
 * Created by PhpStorm.
 * User: 75763
 * Date: 2018/1/30
 * Time: 14:47
 */
use think\Config;
use think\Lang;
use think\Loader;
use think\Request;

/**
 * 插件基类控制器
 * @package think\addons
 */
class PromotionBase extends \think\Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}
